#
# This is free software, lisence use MIT.
# 
# 
# <https://github.com/Chikage0o0/openwrt-packages>
#

name: Merge-upstream
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/upstream.yml'
      - '.gitignore'
#  schedule:
#    - cron: 0 0 * * *

jobs:
  merge:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: Ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: 设置Github账户
      run : |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        sudo timedatectl set-timezone "Asia/Shanghai"

    - name: 同步上游
      run: |
        
        # 删除git缓存以及feeds的文件夹
        git rm -r --cache * >/dev/null 2>&1 &
        rm -rf ./feeds >/dev/null 2>&1
        mkdir feeds && cd feeds

        # miniupnpd支持强行映射
        svn export https://github.com/hzyitc/miniupnpd-openwrt-ptpt52-mod/trunk/miniupnpd

        # uu游戏加速器
        svn export https://github.com/immortalwrt/luci/branches/openwrt-21.02/applications/luci-app-uugamebooster
        svn export https://github.com/immortalwrt/packages/branches/openwrt-21.02/net/uugamebooster

        # vlmcsd
        svn export https://github.com/immortalwrt/luci/branches/openwrt-21.02/applications/luci-app-vlmcsd 
        svn export https://github.com/immortalwrt/packages/branches/openwrt-21.02/net/vlmcsd 

        # ssr-plus
        svn export https://github.com/immortalwrt/luci/branches/openwrt-21.02/applications/luci-app-ssr-plus
        
        # passwall
        svn export https://github.com/Chikage0o0/openwrt-passwall/branches/luci/luci-app-passwall

        # passwall2
        svn export https://github.com/Chikage0o0/openwrt-passwall2/trunk/luci-app-passwall2

        # openclash
        # svn export https://github.com/vernesong/OpenClash/trunk/luci-app-openclash 暂时屏蔽最新版
        svn export https://github.com/vernesong/OpenClash/tags/v0.44.42-beta/luci-app-openclash

        # passwall以及ssr-plus的依赖
        git clone --depth 1 -b packages https://github.com/Chikage0o0/openwrt-passwall
        mv -n `find openwrt-passwall/* -maxdepth 0 -type d` ./ && rm -rf openwrt-passwall
        svn export https://github.com/immortalwrt/packages/branches/openwrt-21.02/net/redsocks2

        # mosdns
        svn export https://github.com/QiuSimons/openwrt-mos/trunk/luci-app-mosdns
        svn export https://github.com/QiuSimons/openwrt-mos/trunk/mosdns

        # 主题
        svn export https://github.com/jerrykuku/luci-theme-argon/trunk ./luci-theme-argon
        svn export https://github.com/jerrykuku/luci-app-argon-config/trunk ./luci-app-argon-config
        # svn export https://github.com/thinktip/luci-theme-neobird/trunk ./luci-theme-neobird 不支持Openwrt最新版
        # svn export https://github.com/Chikage0o0/luci-theme-infinityfreedom/trunk/luci-theme-infinityfreedom 不支持Openwrt最新版

        # 灵缇加速器
        git clone --depth 1 https://github.com/esirplayground/LingTiGameAcc
        git clone --depth 1 https://github.com/esirplayground/luci-app-LingTiGameAcc

        # diskman
        svn export https://github.com/lisaac/luci-app-diskman/trunk/applications/luci-app-diskman

        # Luci-app-socat
        svn export https://github.com/immortalwrt/luci/branches/openwrt-21.02/applications/luci-app-socat

        # Zerotier的面板
        git clone --depth 1 https://github.com/rufengsuixing/luci-app-zerotier
        
        # Realtek 8125 驱动
        svn export https://github.com/csrutil/OpenWrtDrivers/trunk/drivers/r8125

        # luci-app-nat6-helper
        git clone --depth 1 https://github.com/Ausaci/luci-app-nat6-helper

        # 网易云音乐解锁
        svn export https://github.com/maxlicheng/luci-app-unblockmusic/trunk/app luci-app-unblockmusic
        svn export https://github.com/maxlicheng/luci-app-unblockmusic/trunk/UnblockNeteaseMusicGo
        svn export https://github.com/maxlicheng/luci-app-unblockmusic/trunk/UnblockNeteaseMusic

        # 高级设置
        git clone --depth 1 https://github.com/sirpdboy/luci-app-advanced

        # 阿里云webdav
        svn export https://github.com/messense/aliyundrive-webdav/trunk/openwrt/luci-app-aliyundrive-webdav
        svn export https://github.com/messense/aliyundrive-webdav/trunk/openwrt/aliyundrive-webdav

        # koolproxy去广告
        git clone --depth 1 https://github.com/yaof2/luci-app-ikoolproxy
        
    - name: 删除多余文件
      run: |
        rm -rf ./feeds/.svn
        rm -rf ./feeds/*/.git
        rm -rf ./feeds/*/.github
        rm -rf ./feeds/*/.svn
        rm -rf ./feeds/*/README.md
        rm -rf ./feeds/*/LICENSE

    - name: 解决冲突
      run: |
        sed -i 's#../../luci.mk#$(TOPDIR)/feeds/luci/luci.mk#g' ./feeds/*/Makefile
          
    - name: 提交
      run: |
        Emoji=("🎉" "🤞" "✨" "🎁" "🎈" "🎄" "🎨" "💋" "🍓" "🍕" "🍉" "💐" "🌴" "🚀" "🛸" "🗽" "⛅" "🌈" "🔥" "⛄" "🐶" "🏅" "🦄" "🐤")
        git add .
        git commit -m "${Emoji[$[$RANDOM % ${#Emoji[@]}]]} Sync $(date +%Y-%m-%d" "%H:%M:%S)"
        git reset --soft HEAD^
        git add .
        git commit -m "${Emoji[$[$RANDOM % ${#Emoji[@]}]]} Sync $(date +%Y-%m-%d" "%H:%M:%S)"
        git push -f

    - name: 触发编译
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.SECRET_TOKEN }}
        event-type: Compile-IPK

    - name: 删除历史Action记录
      uses: Mattraks/delete-workflow-runs@main
      continue-on-error: true
      with:
        retain_days: 1
        keep_minimum_runs: 3
